language: android
android:
    jdk:
      - openjdk8
    components:
      - tools
      # the current build tools version used by this project
      - build-tools-23.0.3
      # the sdk used to compile the project
      - android-23
      - extra-android-support
      - extra-android-m2repository
      
    before_install:
      - chmod +x gradlew

script: 
  - ./gradlew assembleDebug
  - ./gradlew build jacocoTestReport assembleAndroidTest
after_success:
  - bash <(curl -s https://codecov.io/bash)
